blank_issues_enabled: false
contact_links:
  - name: OpenO Community Support
    url: https://github.com/openo-beta/Open-O/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: https://github.com/openo-beta/Open-O/security/policy
    about: Please report security vulnerabilities here.